version: "3.9"

services:
  postgresql:
    build: ./postgres_db
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  scripts:
    build: ../.
    volumes:
      - ../results:/results
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - default


